### PR TITLE
Added new mesh creator

### PR DESCRIPTION
**Pull request by SirKurt**
It just has basic features for now and has Todo's:
- Make controls easier
- Arrange a editor window gui
- Make it initially create sprite polygon
- Preview mode (preview triangles and how it affects the sprite when control points are moved)
- Other things from the old window

Window can be opened from "Sprites And Bones / Mesh Creator "
How to use the mesh creator (right-click is used for now because handles interrupt the left click event. Didn't have time to fix yet):
- Right click over a vertex to select it
- [Ctrl + right-click] adds vertices / [Shift + right-click] deletes them
- When a vertex is selected, [ctrl/shift + right-click] over the edge can be used to add/remove edges from the selected point to other points 
- [Alt + right-click] adds and removes holes (May be needed for complex meshes)

### CODE REVIEW

**Comment by playemgames** [comment]
Tried it but doesn't seem to triangulate right, also when I tried to use the mesh in the Skin2D component, it literally corrupted all the text in the Unity Editor GUI.  I'll wait till the kinks are worked out :)

**Comment by SirKurt** [comment]
I didn't try it in Skin2D yet. But triangulation worked for me. Are you adding polygon edges? Note that for each edge in the polygon, you should explicitly add them (added edges are rendered green and non-added edges are blue)

**Comment by SirKurt** [comment]
Hello,
I improved it alot and it works wonders for me. Just there is a bug which causes uv mappings to mess up if sprite is rotated. Another problem is controls. If there are so many points, edges may be hard to select but zooming in and selecting or dragging the handle size down works for now.
Also I found the problem about Skin2D. If there is no skeleton or bone in the parent hierarchy of the sprite, It fails to create a skinned mesh and gives errors constantly. Needs a warning that states there should be a skeleton.

**Comment by playemgames** [comment]
Well, I can sorta get it to work, but undo doesn't work and I have no way to reset the points.  Still not quite getting the flow of how it should work.

meshcreator

I'll see if I can get an error message in there somewhere.

**Comment by SirKurt** [comment]
I have thought of a new control mechanism for drawing edges and will implement it this evening. I also plan to add Undo support (I haven't worked with Unity Editor much before, I hope I can).
As to how it works:
The green edges are the defined edges in your mesh. If you add a defined edge, it means this edge will surely be included in the resulting mesh. Now if you want to create a polygon, you should add its outer edges as defined edges, this way when mesh is triangulated, it will take the shape of the polygon. If you want to add a hole, define inner polygon (again you must define inner edges) and optionally you can add hole by alt+click to remove that part in mesh.
I will change how edges are defined though. As it is right now, if you want to define an edge between two points, you must first select the first point, then you must ctrl+click the edge you want to add. I will change it to drawing with mouse between two points with snap support.

**Comment by SirKurt** [comment]
Also, what do you mean by resetting points? Reset to what? Clicking the create polygon from sprite button will return vertices to how they should be. Also in preview mode, even if you change vertex position, when you exit preview mode everything will return to normal.

**Comment by SirKurt** [comment]
I will try to add a tutorial showing practical uses when I think it is stable and usable. I suggest this merge request to stay open and we can discuss here.
If there is some particular feature you want tell me.

**Comment by playemgames** [comment]
The workflow you described sounds better for sure.  As for Undo support you can see how I did it in the SkinMesh script.  As for resetting the points, I meant more of a reset button where it clears everything out to start over.  Yeah I will give it a whirl again after I see how you do it when it is more stable.  I'm a bit swamped right now, so I probably won't get to play with it until later this weekend.  Good work though man, it is better than I can do for sure!

**Comment by playemgames** [comment]
Tried it again but still don't have the hang of it, I'll have to see an animated gif or vid of how you use it.

**Comment by SirKurt** [comment]
Hello. I uploaded a basic video. It shows how to create a mesh in mesh creator. I used auto generation of points but the idea is, the outline of the mesh must be defined (green lines show defined edges). Also other defined edges will be present in resulting mesh triangulation. Controls are as before. To add a defined edge use Ctrl + drag (no click, just drag).
https://www.youtube.com/watch?v=1lSQPwJaFnM&feature=youtu.be

**Comment by playemgames** [comment]
A video is worth a million words!  Thanks that was a tremendous help!  One thing I felt was pretty awkward was the way you make edges, the Ctrl + drag is a bit iffy at times.  Maybe right click to select a point, then just drag it to another without having to press Ctrl.  Also Shift + Click does not remove the edge or point but Shift + Right Click does.  Maybe you can add the subdivision code I have from SkinMesh to create some points from subdivisions.  I had no idea that adding a hole was just marking the inside of a polygon with the Alt + click, I thought I had to draw it separately.  That is nice, but maybe need to alter the description.  Otherwise this is shaping up nicely!

**Comment by SirKurt** [comment]
Yeah, you almost observed all the wrong things :)
Ctrl + drag seems wrong. But once the user understands, it becomes obvious. The reason we can't use left click is, left click is interrupted by handles. We can use right click but I think it makes it harder. Shift + left click should remove an edge as long as it is not near a handle.
About adding holes, that is how Triangle.NET works. When I first started working with Triangle.NET, I thought it was counter-intuitive but it seems like the most efficient thing to do. I will try to visualize holes like areas instead of points later.
As now it operates well and efficient. The only problem is ease of use. To overcome the interruption of left-mouse click, I thought of writing a custom preview window which draws scene and handles events as I want. But I don't think it is worth the work. 
Instead, I am now working on projecting of mecanim animations to 2d and 2d object avatars. I am having progress but seems like it will be harder than I thought initially.

**Comment by playemgames** [comment]
I'll see if I can dig into the code sometime next week, this time is really, really busy for me as I have a baby girl ready to arrive any time now!  So I'll see if I can work on it when I can.  I think right click to start and end an edge is a bit more intuitive than the Ctrl drag, I'll experiment with it a bit later.  Yeah custom preview is not necessary, just have to work around with what we have.  Mecanim 2D to 3D sounds tricky, can't wait to see what kind of solutions you come up with!

**Comment by SirKurt** [comment]
Congrats on baby. You don't have to force yourself working on this. I am doing this because it is fun for me, and I am using it as well. But it feels good to have someone to discuss with.

**Comment by playemgames** [comment]
Not feeling forced at all!  I just feel bad I don't have much time to work on it as much as I'd like right now, don't want you to feel like you are going at it completely solo :)  Soon as I have a good chunk of time to sit down with it, I'll be seeing what I can do to improve it!  Again this is a really neat tool!

**Comment by SirKurt** [comment]
I didn't think it was possible to make adding edges with right click drag because right click moves the scene camera. But with a trick, I disable the scene camera drag when defining segment and it worked.
I tried to add mesh subdividing as you suggested. Seems like another approach will be needed because as it is, it doesn't seem efficient and fails to triangulate time to time.
Also I noticed, with high number of vertices, performance crawls. Since it has to draw each handle for every frame, it was kinda expected. But maybe something can be done.
Still has no undo support and my attempts at implementing undo are fail.
I think this version is stable and usable enough (except for subdividing and undo).

**Comment by playemgames** [comment]
Right clicking and dragging is much more intuitive :)  Unfortunately it broke when I tried to preview the mesh:

"Mesh.vertices is too small. The supplied vertex array has less vertices than are referenced by the triangles array.
UnityEngine.Mesh:set_vertices(Vector3[])
MeshCreator:PreviewMode() (at Assets/SpritesAndBones/Scripts/Editor/MeshCreator.cs:312)
MeshCreator:OnSceneGUI(SceneView) (at Assets/SpritesAndBones/Scripts/Editor/MeshCreator.cs:170)
UnityEditor.DockArea:OnGUI()"

As for subdividing levels you should also have a level 0 to reset the subdivisions back to its initial state.  Without undo support, it can be a pain to try things out with it.  I'll see if I can get some time this week to look into it, been awfully swamped recently though.  To add undo support you mainly need this:

Undo.RecordObject(this, "Undo last action");
EditorUtility.SetDirty(this);

The "Undo last action" string can be any description you want.  There are times you may want to undo the SpriteRenderer object as well.

**Comment by SirKurt** [comment]
I never encountered that error. I will look into it. But it may be ultimately because initial mesh topology is wrong. For example, there shouldn't be any intersecting edges. Triangle.NET usually catches errors like this but sometimes it doesn't. I will add a mechanism which will not add an edge if it is intersecting with any other edge.

This weekend, I started making my game using Sprites and Bones and started noticing things that are hard for a fast workflow. I wrote a new skin creator, which is just like the new mesh creator which you can preview but also with bones and painting mode. I am trying to make it so that it cannot be broken and is easy to use. Because the old skin creator breaks for me usually and I have to recreate the skin. I will commit the new skin creator when I am done with it.

**Comment by playemgames** [comment]
That sounds really interesting, I'll have to see how it works out.  Basically I just created a bunch of points around an image then added the edges around them like in the image above.  Went to preview and got a purple texture and the error.

**Comment by SirKurt** [comment]
If you defined edges exactly as in the image, note that you have intersecting edges. I would add a constraint which prevents adding intersecting edges but this would have to be checked every time a point is moved and an edge is added. And it has a time complexity of N^2 in the number of edges. Something must be sacrificed here.

**Comment by playemgames** [comment]
No I did the edges around the image.

**Comment by playemgames** [comment]
Hi SirKurt, finally got around to working on this, I added undo support, and fixed the error generated from saving the asset.  It doesn't seem to save correctly with the AssetUtility you created so I used the ScriptableObjectUtility instead and it works fine now.  The only thing that is broken with the undo support is segments.  For some reason it is not registering their first and second vertex positions and they remain static.  You have to manually delete and redefine them with the existing vertices, so if you do an undo after creating edges, they just sit there and do not move with the existing vertices.  If you have any ways of fixing the undo support for segments I'm all ears, but this is now a neat little tool for creating custom meshes with full control over edges and holes.  Closing this pull request now since the other changes are not necessary.  You can create a new one with the existing code I put up recently for any new changes.  Thanks for your contribution!

**Pull request closed without merging**
